In [ ]:
import pandas as pd

In [ ]:
from sqlite3 import connect
conn = connect(':memory:')

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

Mounted at /content/drive/

In [ ]:
# model_brand_1 = pd.read_csv("/content/drive/MyDrive/Text (^q^)/Assignment 1/2 - car model.csv") # model-brand provided by class material
# model_brand_2 = pd.read_csv("/content/drive/MyDrive/Text (^q^)/Assignment 1/2 - models.csv") # supplimentary model-brand info dataset from GitHub (https://github.com/abhionlyone/us-car-models-data/blob/master/2022.csv)

In [ ]:
model_brand_1.head(5)

        Brand   Model
0       Acura     ILX
1       Acura     MDX
2       Acura     RDX
3       Acura     TLX
4  Alfa Romeo  Giulia

In [ ]:
model_brand_2.head(5)

   Brand    Model
0  acura  integra
1  acura   Legend
2  acura    vigor
3  acura      rlx
4  acura      ILX

In [ ]:
model_brand_1.to_sql("model_brand_1", conn)
model_brand_2.to_sql("model_brand_2", conn)

In [ ]:
model_brand_merged = pd.read_sql_query("SELECT * FROM model_brand_1 UNION ALL SELECT * FROM model_brand_2", conn) # merge two model-brand info table together
model_brand_merged.head(5)

   index       Brand   Model
0      0       Acura     ILX
1      1       Acura     MDX
2      2       Acura     RDX
3      3       Acura     TLX
4      4  Alfa Romeo  Giulia

In [ ]:
car = pd.read_csv("C:/YICHEN WANG/Course/2022 WINTER/INSY 669/ASSIGNMENT/assignment1/final.csv")
review = pd.read_csv("/content/drive/MyDrive/Text (^q^)/Assignment 1/1 - edmunds_extraction1.csv")

import nltk
nltk.download('punkt')
from nltk.tokenize import word_tokenize

tokenized = []
for i in review["comment"]:
    text = word_tokenize(i)
    for j in range(len(text)):
        if any(text[j]==car['Model']):
            brand = car.loc[car.Model==text[j],'Brand'].iloc[0]
            text[j] = brand
    tokenized.append(text)